### PR TITLE
Update DefaultDynamicLinqCustomTypeProvider constructor to be compatible with microsoft/RulesEngine

### PR DESCRIPTION
**Pull request by StefH**

### CODE REVIEW

**Review by aligneddev — APPROVED** [review]
That looks like it will handle the issue to me.

**Comment by StefH** [comment]
> That looks like it will handle the issue to me.

To be 100% sure, I did create a preview (System.Linq.Dynamic.Core.1.4.4-preview-01) which can be downloaded from MyGet:
https://www.myget.org/F/system-linq-dynamic-core/api/v3/index.json

Can you test this?

**Comment by nmadland** [comment]
Yes will do. Thank you.

**Comment by nmadland** [comment]
We should be back in business. Thank you.

**Comment by StefH** [comment]
Fixing SonarCloud is not needed, because I actually introduced a obsolete and not-used method ;-)

**Comment by nmadland** [comment]
Yes it does. Thank you.

**Comment by nmadland** [comment]
Any idea when a new version will be published to nuget?

**Comment by StefH** [comment]
> Any idea when a new version will be published to nuget?

probably in a few days

**Pull request merged**
