### PR TITLE
Add support for IQueryable.Min and .Max

### PR DESCRIPTION
**Pull request by gregfullman**
Min and Max extension methods for IQueryable were not available.

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Thank you for the pull.

We will look if there is a reason why `Min` and `Max` is still not here in the `DynamicQueryableExtensions` class.

We will look at your pull next week

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by StefH** [comment]
This was addressed before #404

**Comment by gregfullman** [comment]
@StefH I did notice #404 - as far as I could tell it specifically addressed the usage of Min/Max nested within a dynamic expression (e.g. the example ion the dotnetfiddle). It didn't account for the extension methods exposed for the IQueryable interface.

**Comment by JonathanMagnan** [comment]
Hello @gregfullman ,

The v1.2.3 has been released. I also agree on this addresses a different problem.

@StefH if you believe otherwise, let me know what should be done instead

**Pull request merged**
