### PR TITLE
Fix MethodCallExpression when using NullPropagating (np)

### PR DESCRIPTION
**Pull request by StefH**
#432

### CODE REVIEW

**Comment by StefH** [comment]
@JonathanMagnan Some other unit tests fail, so do not merge this PR yet.

**Comment by StefH** [comment]
Hello @JonathanMagnan, I did fix the code + unit tests. If you agree, I can merge this to master.

When that's doneI will start looking at https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/444.

**Comment by JonathanMagnan** [comment]
Hello @StefH ,

I should be able to look at it tomorrow.

**Comment by JonathanMagnan** [comment]
Look good ;)

Let me know if you wish I release during the weekend or wait for the #444 fix

**Pull request merged**
