### PR TITLE
Fix ConstantExpressionWrapper to support Nullable (wip...)

### PR DESCRIPTION
**Pull request by StefH**
https://github.com/StefH/System.Linq.Dynamic.Core/issues/331

### CODE REVIEW

**Comment by StefH** [comment]
https://github.com/StefH/System.Linq.Dynamic.Core/issues/331

**Comment by ascott18** [comment]
@StefH What is the status on this? What remains to be done - anything that someone could help out with?

**Comment by StefH** [comment]
@ascott18 
I could use some help indeed.

See issue #331 which defines another scenario which seems to be not handled correctly by the code.

**Comment by ascott18** [comment]
I'll take a look and see what I can figure out.

**Comment by ascott18** [comment]
@StefH Opened https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/399 that builds on this PR to fix that issue in #331.

**Comment by JonathanMagnan** [comment]
Close this PR as requested by StefH, we will work instead using the pull #399

**Pull request closed without merging**
