### PR TITLE
support for generic (static) methods, thus also support for extension…

### PR DESCRIPTION
**Pull request by dogguts**
this PR provides support for generic methods (as (among others) requested in #386 ), and thus also for generic extension methods.
An actual use case for this whould be the, in EF Core 5.0, introduced  "Collate" extension method, wich has a generic signatue:

```c#
// https://github.com/dotnet/efcore/blob/v5.0.7/src/EFCore.Relational/Extensions/RelationalDbFunctionsExtensions.cs 
public static TProperty Collate<TProperty>(
           [NotNull] this DbFunctions _,
           [NotNull] TProperty operand,
           [NotNull] [NotParameterized] string collation)
```

Also contains additional unit tests

### CODE REVIEW

**Comment by Nokecy** [comment]
Is this PR reviewed? @StefH

**Comment by StefH** [comment]
Not yet.

I'll do it.

Thanks for this PR.

**Comment by StefH** [comment]
@Nokecy 
Can you please resolve merge conflicts?

**Comment by Nokecy** [comment]
@dogguts  Can you please resolve merge conflicts?

**Comment by dogguts** [comment]
resolved 😄

**Comment by Nokecy** [comment]
@StefH  😄

**Pull request merged**
